# Gitpod configuration for Droga Szamana RPG
tasks:
  - name: Run Droga Szamana RPG
    init: |
      echo "🎮 Initializing Droga Szamana RPG..."
      python --version
    command: |
      clear
      echo "================================"
      echo "   DROGA SZAMANA RPG READY!"
      echo "================================"
      echo ""
      echo "To start the game, type:"
      echo "  python main.py"
      echo ""
      echo "For GUI version:"
      echo "  python integrated_gui.py"
      echo ""

vscode:
  extensions:
    - ms-python.python

ports:
  - port: 8080
    onOpen: ignore